on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    environment: SCORING
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      PROJECT_ID: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Run the tests
        run: ./gradlew test jacocoTestReport
      
      - name: Install xml Parser
        run: npm install dom-parser
      
      - name: Update solution
        if: always()
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const fs = require('fs')
            const DomParser = require('dom-parser');

            const file = fs.readFileSync('./build/test-results/test/TEST-com.nuwe.AppTest.xml')
            var parser = new DomParser()
            const dom = parser.parseFromString(file.toString())

            const assertionResults = []

            dom.getElementsByTagName("testcase").forEach((testcase) => {
                testName = testcase.getAttribute("name")
                testPassed = testcase.getElementsByTagName("failure").length === 0
                assertionResults.push(testPassed)
            })
            console.log(assertionResults)

      - name: SonarQube Scan 🚨
        run:  ./gradlew sonarqube
